import {
  LIST_SITES_TOOL,
  SITE_ACTIVE_LIST_TOOL,
  SITE_MATCH_TOOL,
  CREATE_SITE_TOOL,
  UPDATE_SITE_PAUSE_TOOL,
  GET_SITE_PAUSE_TOOL,
  list_sites,
  site_active_list,
  site_match,
  create_site,
  update_site_pause,
  get_site_pause,
} from './site';
import {
  SET_CERTIFICATE_TOOL,
  APPLY_CERTIFICATE_TOOL,
  GET_CERTIFICATE_TOOL,
  DELETE_CERTIFICATE_TOOL,
  LIST_CERTIFICATES_TOOL,
  GET_CERTIFICATE_QUOTA_TOOL,
  set_certificate,
  apply_certificate,
  get_certificate,
  delete_certificate,
  list_certificates,
  get_certificate_quota,
} from './certificate';
import {
  UPDATE_IPV6_TOOL,
  GET_IPV6_TOOL,
  update_ipv6,
  get_ipv6,
} from './ipv6';
import {
  UPDATE_MANAGED_TRANSFORM_TOOL,
  GET_MANAGED_TRANSFORM_TOOL,
  update_managed_transform,
  get_managed_transform,
} from './managedTransform';
import {
  SITE_RECORD_LIST_TOOL,
  CREATE_SITE_A_OR_AAAA_RECORD_TOOL,
  CREATE_SITE_CNAME_RECORD_TOOL,
  CREATE_SITE_TXT_RECORD_TOOL,
  CREATE_SITE_NS_RECORD_TOOL,
  CREATE_SITE_MX_RECORD_TOOL,
  UPDATE_RECORD_TOOL,
  DELETE_RECORD_TOOL,
  LIST_RECORDS_TOOL,
  GET_RECORD_TOOL,
  site_record_list,
  create_site_a_or_aaaa_record,
  create_site_cname_record,
  create_site_txt_record,
  create_site_ns_record,
  create_site_mx_record,
  update_record,
  delete_record,
  list_records,
  get_record,
} from './record';
import { ToolHandlers } from '../../utils/types';

export const SITE_TOOLS = [
  LIST_SITES_TOOL,
  SITE_ACTIVE_LIST_TOOL,
  SITE_MATCH_TOOL,
  CREATE_SITE_TOOL,
  UPDATE_SITE_PAUSE_TOOL,
  GET_SITE_PAUSE_TOOL,
  SET_CERTIFICATE_TOOL,
  APPLY_CERTIFICATE_TOOL,
  GET_CERTIFICATE_TOOL,
  DELETE_CERTIFICATE_TOOL,
  LIST_CERTIFICATES_TOOL,
  GET_CERTIFICATE_QUOTA_TOOL,
  UPDATE_IPV6_TOOL,
  GET_IPV6_TOOL,
  UPDATE_MANAGED_TRANSFORM_TOOL,
  GET_MANAGED_TRANSFORM_TOOL,
  SITE_RECORD_LIST_TOOL,
  CREATE_SITE_A_OR_AAAA_RECORD_TOOL,
  CREATE_SITE_CNAME_RECORD_TOOL,
  CREATE_SITE_TXT_RECORD_TOOL,
  CREATE_SITE_NS_RECORD_TOOL,
  CREATE_SITE_MX_RECORD_TOOL,
  UPDATE_RECORD_TOOL,
  DELETE_RECORD_TOOL,
  LIST_RECORDS_TOOL,
  GET_RECORD_TOOL,
];

export const siteHandlers: ToolHandlers = {
  list_sites,
  site_active_list,
  site_match,
  create_site,
  update_site_pause,
  get_site_pause,
  set_certificate,
  apply_certificate,
  get_certificate,
  delete_certificate,
  list_certificates,
  get_certificate_quota,
  update_ipv6,
  get_ipv6,
  update_managed_transform,
  get_managed_transform,
  site_record_list,
  create_site_a_or_aaaa_record,
  create_site_cname_record,
  create_site_txt_record,
  create_site_ns_record,
  create_site_mx_record,
  update_record,
  delete_record,
  list_records,
  get_record,
};
